Add conditional skip for the vnet_route_leak by bug
sonic-net/sonic-mgmt pull request #10152
Opened 2023-09-27 03:04 UTC by nhe-NV

### Description of PR

Summary: Added a conditional skip to vnet_route_leak test due to bug https://github.com/sonic-net/sonic-mgmt/issues/8374
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205
- [x ] 202305

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2023-11-13 15:42 UTC, roy-sror requested changes
Nana, it seems that there is already such a skip statement:
https://github.com/sonic-net/sonic-mgmt/pull/8864

2023-11-20 11:55 UTC, roy-sror approved these changes

2023-11-21 00:23 UTC, prsunny commented
> Nana, it seems that there is already such a skip statement: #8864

Is this applicable? Can you reply to this?

2023-12-04 18:07 UTC, prsunny approved these changes

2023-12-04 18:07 UTC, merged

2023-12-11 05:56 UTC, nhe-NV commented
@prsunny can you help to backport this to the 202012, 202205 and the 202305 branch?

2023-12-18 04:16 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/11054

2023-12-18 04:16 UTC, mssonicbld commented
Cherry-pick PR to 202205: https://github.com/sonic-net/sonic-mgmt/pull/11055