Ignore the migration error in upgrade path test when downgrading to base version
sonic-net/sonic-mgmt pull request #10427
Opened 2023-10-24 06:56 UTC by congh-nvidia

### Description of PR

Summary:
When downgrading from a newer version to an older one via sonic-installer, there could be package migration error because the older version doesn't contain some packages.
We need to ignore this kind of error in the upgrade path test.
```
tests.common.devices.base:base.py:104 /root/mars/workspace/sonic-mgmt/tests/upgrade_path/upgrade_helpers.py::install_sonic#89: [r-tigon-04] AnsibleModule::reduce_and_add_sonic_images Result => {"failed": true, "msg": "Image installation failed: rc=1, out=efi not supported - exiting without verification

Installing image SONiC-OS-202205_3_rc.13-a8586b250_Internal and setting it as default...
Command: bash /host/downloaded-sonic-image
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in SONiC
ONIE Installer: platform: x86_64-mellanox-r0
onie_platform: x86_64-mlnx_msn4600c-r0
Installing SONiC to /host/image-202205_3_rc.13-a8586b250_Internal
Archive:  fs.zip
   creating: /host/image-202205_3_rc.13-a8586b250_Internal/boot/
  inflating: /host/image-202205_3_rc.13-a8586b250_Internal/boot/config-5.10.0-18-2-amd64  
  inflating: /host/image-202205_3_rc.13-a8586b250_Internal/boot/System.map-5.10.0-18-2-amd64  
  inflating: /host/image-202205_3_rc.13-a8586b250_Internal/boot/initrd.img-5.10.0-18-2-amd64  
  inflating: /host/image-202205_3_rc.13-a8586b250_Internal/boot/vmlinuz-5.10.0-18-2-amd64  
 extracting: /host/image-202205_3_rc.13-a8586b250_Internal/fs.squashfs  
Switch CPU vendor is: GenuineIntel
Switch CPU cstates are: disabled
EXTRA_CMDLINE_LINUX=
Installed SONiC base image SONiC-OS successfully

Command: grub-set-default --boot-directory=/host 0

Command: config-setup backup
Taking backup of current configuration

Command: mkdir -p /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mount -t squashfs /host/image-202205_3_rc.13-a8586b250_Internal/fs.squashfs /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: sonic-cfggen -d -y /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/sonic/sonic_version.yml -t /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/usr/share/sonic/templates/sonic-environment.j2
Command: umount -r -f /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: rm -rf /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mkdir -p /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mount -t squashfs /host/image-202205_3_rc.13-a8586b250_Internal/fs.squashfs /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mkdir -p /host/image-202205_3_rc.13-a8586b250_Internal/rw
Command: mkdir -p /host/image-202205_3_rc.13-a8586b250_Internal/work
Command: mkdir -p /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mount overlay -t overlay -o rw,relatime,lowerdir=/tmp/image-202205_3_rc.13-a8586b250_Internal-fs,upperdir=/host/image-202205_3_rc.13-a8586b250_Internal/rw,workdir=/host/image-202205_3_rc.13-a8586b250_Internal/work /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: mkdir -p /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/var/lib/docker
Command: mount --bind /host/image-202205_3_rc.13-a8586b250_Internal/docker /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/var/lib/docker
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs mount proc /proc -t proc
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs mount sysfs /sys -t sysfs
Command: cp /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/default/docker /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/tmp/docker_config_backup
Command: sh -c echo 'DOCKER_OPTS=\"$DOCKER_OPTS -H unix:// --storage-driver=overlay2 --bip=240.127.1.1/24 --iptables=false --ipv6=true --fixed-cidr-v6=fd00::/80 \"' >> /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/default/docker
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs /usr/lib/docker/docker.sh start
Command: cp /var/lib/sonic-package-manager/packages.json /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/tmp/packages.json
Command: touch /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/tmp/docker.sock
Command: mount --bind /var/run/docker.sock /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/tmp/docker.sock
Command: cp /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/resolv.conf /tmp/resolv.conf.backup
Command: cp /etc/resolv.conf /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/resolv.conf
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs sh -c command -v sonic-package-manager
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs sonic-package-manager migrate /tmp/packages.json --dockerd-socket /tmp/docker.sock -y
Command: chroot /tmp/image-202205_3_rc.13-a8586b250_Internal-fs /usr/lib/docker/docker.sh stop
Command: mv /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/tmp/docker_config_backup /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/default/docker
Command: cp /tmp/resolv.conf.backup /tmp/image-202205_3_rc.13-a8586b250_Internal-fs/etc/resolv.conf
Command: umount -f -R /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: umount -r -f /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
Command: rm -rf /tmp/image-202205_3_rc.13-a8586b250_Internal-fs
, err=Warning: 'sonic_installer' command is deprecated and will be removed in the future
Please use 'sonic-installer' instead
mount: /sys/fs/cgroup/cpu: cgroup already mounted on /sys/fs/cgroup.
mount: /sys/fs/cgroup/cpuacct: cgroup already mounted on /sys/fs/cgroup.
libyang[1]: Unable to get information about \"initrd.img\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"initrd.img.old\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz\" file in \"/\" when searching for (sub)modules (No such file or directory)
libyang[1]: Unable to get information about \"vmlinuz.old\" file i [...]

2023-10-24 06:57 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/upgrade_path/test_upgrade_path.py:73:21: F841 local variable 'base_version' is assigned to but never used<br/>tests/upgrade_path/test_upgrade_path.py:84:42: F821 undefined name 'target_version'<br/><br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..........................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2023-11-28 09:30 UTC, congh-nvidia commented
/azpw run

2023-11-28 09:30 UTC, mssonicbld commented
/AzurePipelines run

2023-11-28 09:31 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/upgrade_path/test_upgrade_path.py:73:21: F841 local variable 'base_version' is assigned to but never used<br/>tests/upgrade_path/test_upgrade_path.py:84:42: F821 undefined name 'target_version'<br/><br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..........................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2023-11-30 03:26 UTC, congh-nvidia commented
Hi @roy-sror, I have moved the fix in PR(https://github.com/sonic-net/sonic-mgmt/pull/10160) to this one, please review.

2023-11-30 03:45 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>ansible/library/reduce_and_add_sonic_images.py:288:5: F841 local variable 'keep_config_db_json' is assigned to but never used<br/><br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..........................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2023-12-10 15:23 UTC, liat-grozovik commented
@yxieca who can review and approve?

2023-12-11 09:58 UTC, roy-sror approved these changes

2023-12-11 21:29 UTC, yxieca requested changes
I suggest separate the change 1 and 2 in to 2 PRs.

Change 1 should not be merged. fast-reboot is designed to work with minigraph parsing. It is not intended to be performed with a port forwarded config_db.json. That might work, but suggest put a control on this behavior and leave the default to remove config_db.json.

2023-12-12 02:43 UTC, congh-nvidia commented
Hi @yxieca , thanks for your comment, please help see if my understanding is correct:
1. when testing upgrade with **fast-reboot**, **remove** the config_db.json
2. when testing upgrade with **warm-reboot**, **keep** the config_db.json
@stepanblyschak could you also help clarify this? Is keeping the config_db.json a necessary action during the upgrade?

2023-12-13 02:24 UTC, congh-nvidia commented
Hi @stepanblyschak , could you help confirm this? According to Ying, we shouldn't keep the config_db.json when testing upgrade with both fast and warm reboot.

2023-12-20 10:41 UTC, stepanblyschak commented
> I suggest separate the change 1 and 2 in to 2 PRs.
> 
> Change 1 should not be merged. fast-reboot is designed to work with minigraph parsing. It is not intended to be performed with a port forwarded config_db.json. That might work, but suggest put a control on this behavior and leave the default to remove config_db.json.

Could you please clarify this part? If I recall correctly loading minigraph disrupts some logic that puts fast reboot flag into DB when upgrading from older SONiC branches that don't have https://github.com/sonic-net/SONiC/blob/master/doc/fast-reboot/Fast-reboot_Flow_Improvements_HLD.md but I need to double check history. What is the requirement and why the device needs to load minigraph after fast-reboot?

2023-12-20 10:52 UTC, stepanblyschak commented
@yxieca Based on my analysis on the issue we faced some time ago:

```We should not remove config_db.json when doing fast upgrade from older branches (prior to 202205).``` Newer branches have implemented fast-reboot over warm-reboot infrastructure and shouldn't have this problem.

The problem that we faced was:

From config-setup script:

```
    if [ x"${WARM_BOOT}" == x"true" ]; then
        echo "Warm reboot detected..."
        disable_updategraph
        do_db_migration
        rm -f /tmp/pending_config_migration
        exit 0
    elif check_all_config_db_present; then
        echo "Use config_db.json from old system..."
        reload_configdb
        do_db_migration
        # Disable updategraph
        disable_updategraph
    elif [ -r ${MINGRAPH_FILE} ]; then
        echo "Use minigraph.xml from old system..."
        reload_minigraph
```

So instead of entering the 2nd branch we fall into 3rd branch that executes "config load_minigraph" that disrupts the DB migration process and SONiC forgets it is running in fast boot mode. The db migrator does not execute https://github.com/sonic-net/sonic-utilities/blob/master/scripts/db_migrator.py#L1015 because the version is up to date.
The new approach (202205+) does not support fast reboot through loading minigraph anyway as it restores the configuration the same way warm reboot does.

2023-12-20 17:36 UTC, yxieca commented
@stepanblyschak , why load minigraph would disrupt the upgrade procedure? fast-reboot has been relying on minigraph conversion to get new config_db since day1. What broke this procedure?

I agree that we would move on to migrating config_db at some point. but this path is not tested thoroughly up to this point. I think having the option to test it is great. But I think the default behavior should stay as minigraph conversion and it should continue working.

2023-12-25 03:44 UTC, congh-nvidia commented
Hi @yxieca, I have moved the fix for ignoring migration error to a new PR #11135 , please review.

2024-01-02 16:26 UTC, yxieca commented
> Hi @yxieca, I have moved the fix for ignoring migration error to a new PR #11135 , please review.

@congh-nvidia the other PR looks good. Can you make keep config_db.json optional and the default is removing for now?

2024-01-03 02:23 UTC, congh-nvidia commented
Hi @yxieca，I will update the fix. 
But before that, @stepanblyschak could you answer Ying's question:
"why load minigraph would disrupt the upgrade procedure? fast-reboot has been relying on minigraph conversion to get new config_db since day1. What broke this procedure?"
Even if we have the option to keep the config_db.json, we need to know on what circumstances it should be used.
Thanks.

2024-02-02 08:49 UTC, congh-nvidia commented
Hi @stepanblyschak , could you answer Ying's question? Do we still need this PR or we should expect fast reboot upgrade always working with minigraph?

2024-02-02 10:15 UTC, stepanblyschak commented
@congh-nvidia Yes, could you please check upgrade with minigraph and if does not work open GH ticket, we can continue discussion about that there.

2024-02-02 13:17 UTC, congh-nvidia commented
> @congh-nvidia Yes, could you please check upgrade with minigraph and if does not work open GH ticket, we can continue discussion about that there.

Thanks @stepanblyschak, in this case I'm closing this PR.

2024-02-02 13:17 UTC, closed without merging