custom acl table test failure in dualtor-aa fix
sonic-net/sonic-mgmt pull request #11635
Opened 2024-02-05 15:44 UTC by AnantKishorSharma

### Description of PR
In Active-Active DUAL TOR setup, we have the following two important constraints to maintain link state of TORs:
1. gRPC communication between TORs and gRPC server (nic_simualtor).
2. Heartbeat between TORs and server (icmp_responder).

Issue-1 with the failing testcases in test_custom_acl_table.py is, it is fundamentally verifying the INGRESS ACL functionality and the ACLs being used in the test case are not aware of the above 2 points. The moment we apply the INGRESS ACL, it starts blocking the above-mentioned control packets. This results in links in randomly selected TORs going in STANDBY mode, causing test case failure.

Issue-2 with the failing test case in test_custom_acl_table.py is, it does not consider the possibility of test pkts going to unselected ToR  in A/A setup

As a fix, the proposal is to create a “pin hole” in the INGRESS ACL rule and, to configure the ACL rules on both the Active ToRs and check the counter on both the ToRs,, so that we can verify the ACL functionality. Please note that we are planning to add ACL RULES to accept the packets corresponding to ‘loopback2’ and ‘Loopback3’ in the DUAL TOR A-A Setup.

Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/11632

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305
- [ ] 202311

### Approach
#### What is the motivation for this PR?
ACL test case failure in A/A scenario

#### How did you do it?
Added checks for dualtor-aa at relevant places in the test to configure custom ACL tables on both the ToRs and added rules to allow control pkts

#### How did you verify/test it?
Verified that the custom ACL table test case PASS in A/A Setup

#### Any platform specific information?
NA

#### Supported testbed topology if it's a new test case?
NA

### Documentation
NA

2024-02-05 15:45 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/acl/custom_acl_table/test_custom_acl_table.py:300:19: E702 multiple statements on one line (semicolon)<br/><br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..........................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2024-03-01 12:23 UTC, bpar9 requested changes

2024-03-02 05:59 UTC, AnantKishorSharma commented on tests/acl/custom_acl_table/test_custom_acl_table.py
> +def test_custom_acl(rand_selected_dut, rand_unselected_dut, tbinfo, ptfadapter,
No

2024-03-02 07:12 UTC, AnantKishorSharma commented
> @AnantKishorSharma , can you also verify that custom ACL table test passes on T0 topology with your changes
Verified.
```
-------------------------------- generated xml file: /data/tests/logs/tr_2024-03-02-06-52-28.xml ---------------------------------
INFO:root:Can not get Allure report URL. Please check logs
----------------------------------------------------- live log sessionfinish -----------------------------------------------------
07:07:49 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
=========================================== 1 passed, 22 warnings in 920.21s (0:15:20) ===========================================
sonic@sonic-ucs-m6-2:/data/tests$ ./run_tests.sh -n t0-64-2 -d mth-t0-64 -l debug -e -s -O -u -e --disable_loganalyzer -c acl/custom_acl_table/test_custom_acl_table.py
```

2024-03-07 07:32 UTC, XuChen-MSFT approved these changes
LGTM, and pass local test on 202305 branch

2024-03-07 07:55 UTC, merged

2024-03-13 23:25 UTC, jamesan47 commented
Hi @kevinskwang , please help with double commit to 202305 and 202311.

2024-03-20 06:20 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-mgmt/pull/12056

2024-03-20 06:20 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/12057