ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode
sonic-net/sonic-mgmt pull request #11892
Opened 2024-03-05 05:42 UTC by santoss3

### Description of PR
In Active-Active DUAL TOR setup, we have the following two important constraints to maintain link state of TORs:

1. gRPC communication between TORs and gRPC server (nic_simualtor).
2. Heartbeat between TORs and server (icmp_responder).

The issue with the failing testcases in test_acl.py is, it is fundamentally verifying the INGRESS ACL functionality and the ACLs being used in the testcase are not aware of the above 2 points. The moment we apply the INGRESS ACL, it starts blocking the above-mentioned control packets. This results in links in both TORs going in STANDBY mode, causing testcase failure.

As a fix, the proposal is to create a “pin hole” in the INGRESS ACL rule, to ensure that the link status remain Active-Active, so that we can verify the ACL functionality. Please note that we are planning to add ACL RULES to accept the packets corresponding to ‘loopback2’ and ‘Loopback3’ in the DUAL TOR Setup.

Summary:
Fixes # (issue)

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [X] 202205
- [X] 202305
- [X] 202311

### Approach
#### What is the motivation for this PR?
ACL testcases failure in A/A scenario

#### How did you do it?
Added pin hole in the ACL under test to accept ICMP Heart Beat.

#### How did you verify/test it?
Verified that the ACL testcases PASS in A/A Setup

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-03-05 05:43 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/acl/test_acl.py:1185:21: E128 continuation line under-indented for visual indent<br/>tests/acl/test_acl.py:1190:21: E128 continuation line under-indented for visual indent<br/>tests/acl/test_acl.py:1224:21: E128 continuation line under-indented for visual indent<br/>tests/acl/test_acl.py:1228:21: E128 continuation line under-indented for visual indent<br/><br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..........................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2024-03-05 06:03 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Failed<br/>- hook id: check-ast<br/>- exit code: 1<br/><br/>tests/acl/test_acl.py: failed parsing with CPython 3.8.10:<br/><br/>Traceback (most recent call last):<br/>File "/home/AzDevOps/.cache/pre-commit/repo_dws4msa/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/check_ast.py", line 21, in main<br/>ast.parse(f.read(), filename=filename)<br/>File "/usr/lib/python3.8/ast.py", line 47, in parse<br/>return compile(source, filename, mode, flags,<br/>File "tests/acl/test_acl.py", line 1182<br/>sonichost = dut.get_asic_or_sonic_host(None)<br/>^<br/>TabError: inconsistent use of tabs and spaces in indentation<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2024-03-06 03:54 UTC, bpar9 requested changes
LGTM. Can you also verify the ACL test with regular T0 topology with your changes.

2024-03-15 00:42 UTC, santoss3 commented
Updating test result for T0, AA, AS Setup runs.

T0
==
SKIPPED [8] acl/test_acl.py:929: Only run for ingress
SKIPPED [400] acl/test_acl.py:423: IPV6 ACL test not currently supported on t0 testbeds
=========================================================== 384 passed, 416 skipped, 1538 warnings in 4356.63s (1:12:36) ===========================================================
INFO:root:Can not get Allure report URL. Please check logs
sonic@sonic-ucs-m6-2:/data/tests$


A/S
===
collected 1 item                                                                                                                                                                  

acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ipv4-ingress-uplink->downlink-default-Vlan1000] PASSED                    

A/A
==
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
--------------------------------------------------------- generated xml file: /data/tests/logs/tr_2024-03-14-14-59-00.xml ---------------------------------------------------------
=================================================================== 1 passed, 6 warnings in 1087.54s (0:18:07) ====================================================================
INFO:root:Can not get Allure report URL. Please check logs
sonic@sonic-ucs-m6-1:/data/tests$
sonic@sonic-ucs-m6-1:/data/tests$
sonic@sonic-ucs-m6-1:/data/tests$
sonic@sonic-ucs-m6-1:/data/tests$
sonic@sonic-ucs-m6-1:/data/tests$ ./run_tests.sh -n m64-dtor-yy41 -u -c acl/test_acl.py::TestBasicAcl::test_source_ip_match_forwarded[ipv4-ingress-uplink-\>downlink-default-Vlan1000] -f ../ansible/testbed.yaml

2024-03-15 03:37 UTC, merged

2024-03-18 16:47 UTC, jamesan47 commented
Hi @kevinskwang , could you help with double comitting to 202305 and 202311 as well?

2024-04-01 04:39 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-mgmt/pull/12248

2024-04-01 04:39 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/12249