Fixing global_pause attribute and speed typecasting
sonic-net/sonic-mgmt pull request #12202
Opened 2024-03-27 20:02 UTC by selldinesh

### Description of PR

Summary: Fixing the collateral caused by https://github.com/sonic-net/sonic-mgmt/pull/11400 and the speed mode typecasting to int
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### Approach
#### What is the motivation for this PR?
Fixing the collateral caused by https://github.com/sonic-net/sonic-mgmt/pull/11400 and the speed mode typecasting to int
#### How did you do it?

#### How did you verify/test it?
added the global_pause attribute to verify_pause_frame_count_dut fixture in multidut_helper file
#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-03-28 18:37 UTC, developfast commented
Isn't `speed_gbps` is multiple of 1000s (since it's in Mb), so it will be typecasted to int? Are you going more granular than that?

2024-03-28 18:38 UTC, developfast requested changes
As comment above

2024-03-28 21:12 UTC, selldinesh commented
> Isn't `speed_gbps` in multiple of 1000s (since it's in Mb), so it will be typecasted to int? Are you going more granular than that?

the speed that was returned was speed_100.0_gbps instead of speed_100_gbps, that is why this change was submitted

2024-04-11 21:54 UTC, rraghav-cisco commented
I applied this diff, but the problem persists.
<img width="1792" alt="Screenshot 2024-04-11 at 2 53 27 PM" src="https://github.com/sonic-net/sonic-mgmt/assets/58446052/6ca12d26-8c7f-426e-95cb-2fb798cfe487">

The DUT counts it as a non-global pause:
```
root@yy39top-lc4:/home/cisco# show pfc count | head
Last cached time was 2024-04-11T21:41:50.139290
    Port Rx    PFC0    PFC1    PFC2    PFC3    PFC4       PFC5    PFC6    PFC7
-----------  ------  ------  ------  ------  ------  ---------  ------  ------
  Ethernet0       0       0       0       0       0  1,617,164       0       0
  Ethernet8       0       0       0       0       0          0       0       0
 Ethernet16       0       0       0       0       0          0       0       0
 Ethernet24       0       0       0       0       0          0       0       0
 Ethernet32       0       0       0       0       0          0       0       0
 Ethernet40       0       0       0       0       0          0       0       0
 Ethernet48       0       0       0       0       0          0       0       0
root@yy39top-lc4:/home/cisco# 
```

2024-04-12 23:31 UTC, developfast commented
@rraghav-cisco you don't appear to be running the global pause test? Which test is it? class enable vector is set for priority 5 hence you see pfc frames rx for that priority.

2024-05-10 19:54 UTC, abdosi commented
@rraghav-cisco : can you double check ?  It seems same change has been done by you: https://github.com/sonic-net/sonic-mgmt/pull/11694 so this should work .

Please review.

2024-05-20 17:36 UTC, selldinesh commented
Hi @developfast ,
Request to approve this PR

2024-06-12 07:37 UTC, abdosi commented
Fixing the collateral caused by https://github.com/sonic-net/sonic-mgmt/pull/11400 and the speed mode typecasting to int

2024-06-12 07:38 UTC, merged

2024-06-13 17:10 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-mgmt/pull/13289