Adding ansible file samples for snappi-sonic
sonic-net/sonic-mgmt pull request #12314
Opened 2024-04-04 22:55 UTC by selldinesh

### Description of PR

Summary: Adding ansible file samples for snappi-sonic group
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### Approach
#### What is the motivation for this PR?
Adding ansible file samples for snappi-sonic inorder to run snappi_tests cases on the go
#### How did you do it?
Tested on arista dut
#### How did you verify/test it?
This was tested locally in our setup, this includes the devices , links and credentials used for ixnetwork api server
#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-04-04 22:57 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Failed<br/>- hook id: end-of-file-fixer<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing ansible/testbed.csv<br/>Fixing ansible/files/sonic_snappi-sonic_links.csv<br/><br/>check yaml...............................................................Passed<br/>check for added large files..............................................Passed<br/>check python ast.....................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..............................................Passed<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2024-04-09 23:10 UTC, developfast commented
@wangxin can these sample files be merged to master? These are example devices

2024-04-19 15:57 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The pre-commit check is a mandatory check, please fix detected issues.

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Failed<br/>- hook id: end-of-file-fixer<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing ansible/testbed.csv<br/>Fixing ansible/files/sonic_snappi-sonic_links.csv<br/><br/>check yaml...............................................................Passed<br/>check for added large files..............................................Passed<br/>check python ast.....................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/>check conditional mark sort..............................................Passed<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2024-05-09 16:55 UTC, selldinesh commented
/azpw run

2024-05-09 16:55 UTC, mssonicbld commented
/AzurePipelines run

2024-05-20 15:43 UTC, selldinesh commented
/azpw run

2024-05-20 15:43 UTC, mssonicbld commented
/AzurePipelines run

2024-05-20 20:01 UTC, selldinesh commented
Hi @developfast ,
Request to approve this PR

2024-06-06 00:37 UTC, sdszhang commented on tests/snappi_tests/README.md
pls add the snappi package installation steps.

2024-06-06 01:27 UTC, sdszhang requested changes
Waiting on update of README for snappi package

2024-06-12 07:41 UTC, abdosi commented
@selldinesh :please resolve conflict.

2024-06-12 21:27 UTC, selldinesh commented on tests/snappi_tests/README.md
added the steps

2024-06-12 21:31 UTC, closed without merging

2024-06-12 23:04 UTC, selldinesh commented
reopened https://github.com/sonic-net/sonic-mgmt/pull/13245