Change hardcoded PFC_STORM_TEST_PORT to choose from available interfaces
sonic-net/sonic-mgmt pull request #12399
Opened 2024-04-11 00:01 UTC by justin-wong-ce

### Description of PR

Summary:
Move logic that chooses PFC_STORM_TEST_PORT dynamically from 202311 to 202305

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [ ] 202311

### Approach
#### What is the motivation for this PR?
In 202305's `tests/telemetry/events/swss_events.py`, `PFC_STORM_TEST_PORT` is hardcoded to use `Ethernet4`, which may not be available for testing on some configurations.

#### How did you do it?
There already is logic on 202305 and master that dynamically selects the port for testing. Backporting that logic back to 202305.

#### How did you verify/test it?
Test machine without `Ethernet4` can now continue running the test.

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-04-12 23:26 UTC, zbud-msft commented
This looks like a backport of https://github.com/sonic-net/sonic-mgmt/commit/a55ece70e0ff4e408e1255797e1449175a6a02c4, but we are missing the random.seed(), can you double check?

2024-04-12 23:27 UTC, zbud-msft requested changes

2024-04-12 23:27 UTC, zbud-msft commented on tests/telemetry/events/swss_events.py
missing random.seed(10)?

2024-04-13 03:39 UTC, StormLiangMS commented
hi @justin-wong-ce could you check the comment and failed RP test?

2024-04-13 04:57 UTC, justin-wong-ce commented
> This looks like a backport of [a55ece7](https://github.com/sonic-net/sonic-mgmt/commit/a55ece70e0ff4e408e1255797e1449175a6a02c4), but we are missing the random.seed(), can you double check?

Sorry, it is indeed that backport. If you could backport that to 202305 as well that will be great. Will close PR after.

2024-04-16 23:21 UTC, justin-wong-ce commented
> hi @justin-wong-ce could you check the comment and failed RP test?

The checks seem to be fine, which test are you referring to?

2024-05-09 04:18 UTC, zbud-msft commented
LGTM

2024-05-09 04:18 UTC, zbud-msft approved these changes

2024-05-09 04:20 UTC, StormLiangMS approved these changes
LGTM

2024-05-09 04:20 UTC, merged