Adding -F flag for a test list file for testsuites
sonic-net/sonic-mgmt pull request #13308
Opened 2024-06-14 20:11 UTC by arista-nwolfe

Adding a new option `-F` to `run_tests.sh` to pass a file containing tests.
This option extracts the tests from the file and puts them into the `TEST_CASES` variable (used by `-c` argument).
This opens the door to store files with subsets of tests (testsuites) to get coverage of certain areas without having to rerun all the tests.

Example use case:
```
> cat testsuites/platform_sanity
acl/test_acl.py::TestBasicAcl
decap/test_decap.py
fib/test_fib.py::test_fib::test_basic_fib
pfcwd/test_pfc_config.py::TestPfcConfig
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions
qos/test_qos_sai.py::TestQosSai::testQosSaiDot1pQueueMapping
qos/test_qos_sai.py::TestQosSai::testQosSaiDscpQueueMapping
qos/test_qos_sai.py::TestQosSai::testQosSaiDwrr
qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit
qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark
voq/test_fabric_reach.py
voq/test_voq_fabric_status_all.py
voq/test_voq_init.py
voq/test_voq_ipfwd.py::TestFPLinkFlap::test_front_panel_linkflap_port
voq/test_voq_ipfwd.py::TestTableValidation
voq/test_voq_ipfwd.py::TestVoqIPFwd
voq/test_voq_nbr.py::TestNeighborLinkFlap
voq/test_voq_nbr.py::test_voq_nbr::test_neighbor_clear_one
voq/test_voq_nbr.py::test_voq_nbr::test_neighbor_hw_mac_change
```
```
sudo ./run_tests.sh -n ardut -u -m debug -F testsuites/platform_sanity -x
TEST_CASES:            acl/test_acl.py::TestBasicAcl
decap/test_decap.py
fib/test_fib.py::test_fib::test_basic_fib
pfcwd/test_pfc_config.py::TestPfcConfig
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions
qos/test_qos_sai.py::TestQosSai::testQosSaiDot1pQueueMapping
qos/test_qos_sai.py::TestQosSai::testQosSaiDscpQueueMapping
qos/test_qos_sai.py::TestQosSai::testQosSaiDwrr
qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueue
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXoffLimit
qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit
qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark
voq/test_fabric_reach.py
voq/test_voq_fabric_status_all.py
voq/test_voq_init.py
voq/test_voq_ipfwd.py::TestFPLinkFlap::test_front_panel_linkflap_port
voq/test_voq_ipfwd.py::TestTableValidation
voq/test_voq_ipfwd.py::TestVoqIPFwd
voq/test_voq_nbr.py::TestNeighborLinkFlap
voq/test_voq_nbr.py::test_voq_nbr::test_neighbor_clear_one
voq/test_voq_nbr.py::test_voq_nbr::test_neighbor_hw_mac_change
+ echo 'TEST_CASES_FILE:       testsuites/platform_sanity'
TEST_CASES_FILE:       testsuites/platform_sanity
```

2024-06-19 21:50 UTC, wenyiz2021 requested changes

2024-06-19 21:50 UTC, wenyiz2021 commented on tests/run_tests.sh
>      else
can you add a warning after this `else` condition, to avoid user input both TEST_CASES_FILE and TEST_CASES?

2024-06-20 18:29 UTC, wenyiz2021 approved these changes

2024-06-20 18:29 UTC, wenyiz2021 commented
LGTM

2024-06-20 21:12 UTC, arlakshm commented
@wangxin, can you please sign off on this change

2024-07-08 22:37 UTC, vmittal-msft approved these changes

2024-07-18 05:26 UTC, merged