add conditional mark to skip LLDP and SNMP testcases for standalone topo
sonic-net/sonic-mgmt pull request #14397
Opened 2024-09-03 07:38 UTC by Janetxxx

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

### Approach
#### What is the motivation for this PR?
Fix failed tests in ```test_snmp_default_route.py```, ```test_snmp_loopback.py```, and ```test_lldp.py```
#### How did you do it?
Use conditional mark plugin to skip certain testcases. 
Skip SNMP testcase as t0-standalone-32 topology has no neighbor VMs, and SNMP queries will be executed from the neighbor VM.
Skip LLDP test as no LLDP neighbors detected in the standalone topo. 

#### How did you verify/test it?
Validate it in internal setup
In ```snmp/test_snmp_loopback.py```:
```
========================================================================================== short test summary info ===========================================================================================
SKIPPED [2] snmp/test_snmp_loopback.py:13: Skipping LLDP test because standalone topology has no neighbor VMs, and SNMP queries will be executed from the neighbor VM.
======================================================================================= 2 skipped, 1 warning in 27.84s =======================================================================================
```
In ```snmp/test_snmp_default_route.py```:
```
========================================================================================== short test summary info ===========================================================================================
SKIPPED [1] snmp/test_snmp_default_route.py: Skipping LLDP test because standalone topology has no default routes.
======================================================================================= 1 skipped, 1 warning in 30.35s =======================================================================================
```
In ```lldp/test_lldp.py```:
```
========================================================================================== short test summary info ===========================================================================================
SKIPPED [2] lldp/test_lldp.py: Skipping LLDP test because the topology is t0-standalone-32, No LLDP neighbors detected
======================================================================================= 2 skipped, 1 warning in 30.49s =======================================================================================
```
#### Any platform specific information?
str3-7060x6-64pe-1
#### Supported testbed topology if it's a new test case?
t0-standalone-32
### Documentation

2024-09-03 08:50 UTC, yutongzhang-microsoft requested changes
Hi, @Janetxxx , you don't need to create a new yaml file. Just add them into `tests_mark_conditions.yaml`

2024-09-03 09:14 UTC, wangxin submitted a review, later dismissed

2024-09-03 09:56 UTC, Janetxxx commented
> Hi, @Janetxxx , you don't need to create a new yaml file. Just add them into `tests_mark_conditions.yaml`

Thanks @yutongzhang-microsoft , I've appended the newly added conditional marker to the existing tests_mark_conditions.yaml

2024-09-03 10:14 UTC, Pterosaur approved these changes

2024-09-03 10:22 UTC, yutongzhang-microsoft approved these changes

2024-09-04 04:34 UTC, Pterosaur approved these changes

2024-09-05 01:03 UTC, wangxin approved these changes

2024-09-05 01:04 UTC, merged

2024-09-12 04:29 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-mgmt/pull/14537

2024-09-12 04:29 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-mgmt/pull/14538