Skipping test_static_route on Cisco 8122
sonic-net/sonic-mgmt pull request #15272
Opened 2024-10-30 07:53 UTC by AnantKishorSharma

**What is the motivation for this PR?**
All 3 tests in test_static_route are failing on 8122.
Tests are failing because “show flowcnt-route stats“ does not show the 1 test pkt that the test has sent.
“show flowcnt-route stats“ does not show the test pkt because counter config itself failed.
Counter config failed because FLOW_COUNTER_CAPABILITY was enabled recently on ASIC/SDK side for 8122 but 'enable_forwarding_route_counter' is not enabled on SONiC/asic_cfg.json on 8122.
'enable_forwarding_route_counter' is not enabled on SONiC/asic_cfg.json on 8122 because with the current LPM profile we can support max 50K routes+prePrefix Counter enabled. EDVT team wanted to test higher scale, and the request was to support higher scale. If we want to support higher scale we need to modify the LPM profile, that changes the MAC table, prefix table sizes, and see its impact. Currently MSFT is not asking for this support, for time being we can Skip this, enable it once we have higher per prefix counter support.

As the feature is not enabled for this platform, need to skip this testcase

**How did you do it?**
Added a skip condition for test_static_route for 8122 platform 

**Type of change** 
-Test modification

**Back port request** 
-202311
-202405

**How did you verify/test it?**
Ran test_static_router.py on 8122 and verified it was skipped.
```
--------------------- generated xml file: /run_logs/ananshar/route/test_static_route_2024-10-21-03-14-31.xml ---------------------
INFO:root:Can not get Allure report URL. Please check logs

----------------------------------------------------- live log sessionfinish -----------------------------------------------------
03:14:52 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
==================================================== short test summary info =====================================================
SKIPPED [2] route/test_static_route.py: Test not supported for 201911 images or older. Does not apply to standalone topos. Not supported on cisco-8122 platform
SKIPPED [1] route/test_static_route.py:350: Test not supported for 201911 images or older. Does not apply to standalone topos. Not supported on cisco-8122 platform
SKIPPED [1] route/test_static_route.py:371: Test not supported for 201911 images or older. Does not apply to standalone topos. Not supported on cisco-8122 platform
================================================= 4 skipped, 1 warning in 20.15s =================================================
sonic@sonic-ucs-m6-24:/data/tests$ 
```

2024-10-30 07:58 UTC, AnantKishorSharma commented
Hi @wsycqyz , @bpar9 , please review. rc is same as https://github.com/sonic-net/sonic-mgmt/pull/15017

2024-10-30 08:17 UTC, bpar9 requested changes
can you please edit the description to remove EDVT and Customer names similar to how its described in #15017

2024-10-30 08:27 UTC, AnantKishorSharma commented
> Hi @wsycqyz , @bpar9 , please review. rc is same as #15017

done

2024-10-31 06:21 UTC, wsycqyz approved these changes
lğtm

2024-10-31 08:52 UTC, kevinskwang commented
@AnantKishorSharma  could you set enable_forwarding_route_counter in next image?

2024-11-04 03:08 UTC, AnantKishorSharma commented
> @AnantKishorSharma could you set enable_forwarding_route_counter in next image?

@rajendrat , can we do that in next image?

2024-11-12 07:28 UTC, wsycqyz commented
@rajendrat Can you help close the conversation?

2024-11-15 01:22 UTC, merged

2024-11-15 01:38 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-mgmt/pull/15576