Fix acl/test_stress_acl.py invalid interface name
sonic-net/sonic-mgmt pull request #15796
Opened 2024-11-28 18:43 UTC by justin-wong-ce

### Description of PR
Fix acl/test_stress_acl.py using bad interface name for ACL table creation

Summary:
Fixes # (issue)
In `acl/test_stress_acl.py`, it attempts to retrieve an interface that can be used to create a ACL table. DUTs with and without PortChannels require different methods respectively.

Currently, it checks by filtering with topo. However, some topology flags can have configurations that have or not have PortChannels, making topos no longer a sufficient check - in some topos the test will fail with:
```
Error: Failed to parse ACL table config: exception=Cannot bind ACL to specified port Ethernet136
```

Reproducible by manually running the following on the DUT:
```
config acl add table DATAACL L3 -s ingress -p Ethernet0
^FAILS
config acl add table DATAACL L3 -s ingress -p PortChannel101
^WORKS
```

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

### Approach
#### What is the motivation for this PR?

#### How did you do it?
Fix by checking if a PortChannel exists. If it does - use it. If it does not - fallback on the secondary method to retrieve a normal interface name if its a not a dualtor topo (due to
https://github.com/sonic-net/sonic-mgmt/pull/6960).

#### How did you verify/test it?
Test no longer fails creating an ACL table on a t1 topo with PortChannels.
Tested with Arista HwSkus on t0, t1, t2, and mx topologies.

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-12-05 02:48 UTC, StormLiangMS commented
hi @bingwang-ms could you help to take a look?

2024-12-05 02:48 UTC, StormLiangMS submitted a review, later dismissed
LGTM

2024-12-05 16:51 UTC, bingwang-ms commented
@justin-wong-ce Can you help me understand why there is no portchannel for test on dualtor platform?

2024-12-05 17:10 UTC, justin-wong-ce commented
> @justin-wong-ce Can you help me understand why there is no portchannel for test on dualtor platform?

I decided to handle dualtor differently because of this previous pull request: https://github.com/sonic-net/sonic-mgmt/pull/6960

2024-12-05 17:15 UTC, bingwang-ms commented
> > @justin-wong-ce Can you help me understand why there is no portchannel for test on dualtor platform?
> 
> I decided to handle dualtor differently because of this previous pull request: #6960:
> 
> ```
> What is the motivation for this PR?
> In acl stress test, ACL table creation can be failed on dualtor platform because of insufficient resources
> The test case only add/delete a same rule, which is not the real scenario in production
> ```
> 
> I am not too familiar with PortChannels on dualtor but I think sometimes it is not available based on the PR adding dualtor support to the test.

Thanks for the reply. Portchannels should always be available on dualtor platform. 
@xwjiang-ms Can you please help review & comment?

2024-12-12 04:19 UTC, xwjiang-ms commented on tests/acl/test_stress_acl.py
> +    ports = list(mg_facts['minigraph_portchannels'])
mx topo don't have portchannel

2024-12-12 04:23 UTC, xwjiang-ms commented on tests/acl/test_stress_acl.py
> +        pytest.skip('No portchannels available in dualtor topo or no interfaces found on DUT')
I think it's unnecessary to add `in dualtor topo` because it's a common message

2024-12-12 04:24 UTC, xwjiang-ms requested changes
LGTM

2024-12-12 04:33 UTC, xwjiang-ms approved these changes

2024-12-12 13:55 UTC, StormLiangMS commented on tests/acl/test_stress_acl.py
> +    ports = list(mg_facts['minigraph_portchannels'])
hi @justin-wong-ce I had a discussion with Xiawei, quote from his response
"""
The purpose is to bind acl to a upstream port, both pc or eth should work, I remember when I write the case, some tb do not have data acl table, so I used pc, but I checked again this afternoon and found t0/t1/dualtor/mx all have data acl table
"""
the port selection logic could be, take pc first, if no, check the dataacl ports. But there should be no difference for dualtor, could we remove dualtor condition check from line 96, it is a little confusing.

2024-12-13 07:53 UTC, mssonicbld commented
/azp run

2024-12-19 04:19 UTC, StormLiangMS approved these changes
LGTM

2024-12-19 04:19 UTC, merged

2024-12-19 04:20 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-mgmt/pull/16155

2024-12-19 06:12 UTC, mssonicbld commented
Cherry-pick PR to 202411: https://github.com/sonic-net/sonic-mgmt/pull/16156

2025-02-14 04:41 UTC, nhe-NV commented
@r12f  This PR also needed for the 202412 branch, can you help to merge it also to 202412 branch?

2025-02-18 19:40 UTC, r12f commented
already included in 202411, removing 202412 tag.