Add an optional full coverage multi_asic elastic test job in pipeline
sonic-net/sonic-mgmt pull request #15965
Opened 2024-12-10 00:12 UTC by BYGX-wcr

### Description of PR

Summary: Add an optional multi_asic-kvm-t1 test job that runs on all T1 cases in the pipeline to discover existing and incoming T1 test cases that fail on the multi-asic testbed. 

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### Approach
#### What is the motivation for this PR?

Onboard multi-asic kvm t1 testbed for all t1 testcases

#### How did you do it?

Add an optional pipeline job

#### How did you verify/test it?

#### Any platform specific information?

multi-asic

#### Supported testbed topology if it's a new test case?

t1

### Documentation

2024-12-10 01:01 UTC, wenyiz2021 approved these changes

2024-12-10 01:03 UTC, wenyiz2021 commented
instead of merging this PR.
should we take the full coverage multi-asic PR checker result in this PR https://dev.azure.com/mssonic/build/_build/results?buildId=717417&view=results for ref of what tests should be excluded?

2024-12-10 01:45 UTC, BYGX-wcr commented
> instead of merging this PR. should we take the full coverage multi-asic PR checker result in this PR https://dev.azure.com/mssonic/build/_build/results?buildId=717417&view=results for ref of what tests should be excluded?

Yes, we can use this pipeline result to identify the tests that failed on the multi-asic testbed. Yet, we probably need to fix them instead of exclude them to make the multi-asic testbed as a mandatory checker.

2024-12-10 18:21 UTC, wenyiz2021 commented
> > instead of merging this PR. should we take the full coverage multi-asic PR checker result in this PR https://dev.azure.com/mssonic/build/_build/results?buildId=717417&view=results for ref of what tests should be excluded?
> 
> Yes, we can use this pipeline result to identify the tests that failed on the multi-asic testbed. Yet, we probably need to fix them instead of exclude them to make the multi-asic testbed as a mandatory checker.

I mean, we don't necessary need to merge this PR

2024-12-18 22:43 UTC, mssonicbld commented
/azp run

2024-12-18 23:14 UTC, mssonicbld commented
/azp run

2024-12-18 23:37 UTC, mssonicbld commented
/azp run

2024-12-19 01:40 UTC, mssonicbld commented
/azp run

2024-12-19 01:47 UTC, mssonicbld commented
/azp run

2024-12-20 00:20 UTC, mssonicbld commented
/azp run

2024-12-20 17:35 UTC, mssonicbld commented
/azp run

2024-12-26 20:14 UTC, mssonicbld commented
/azp run

2024-12-27 06:03 UTC, yutongzhang-microsoft requested changes

2024-12-27 06:03 UTC, yutongzhang-microsoft commented on .azure-pipelines/test_plan.py
> +                parsed_script, parsed_specific_param = get_test_scripts(args.test_set, incoming_test_scripts)
Here, you want to add the incoming test scripts dynamically into PR testing, right?

2024-12-27 19:11 UTC, mssonicbld commented
/azp run

2024-12-28 01:50 UTC, mssonicbld commented
/azp run

2025-01-31 23:13 UTC, mssonicbld commented
/azp run

2025-02-01 00:16 UTC, mssonicbld commented
/azp run

2025-02-26 23:18 UTC, BYGX-wcr commented
/azpw run

2025-02-26 23:18 UTC, mssonicbld commented
/AzurePipelines run

2025-02-27 00:15 UTC, mssonicbld commented
/azp run

2025-03-18 20:28 UTC, BYGX-wcr commented
not needed

2025-03-18 20:28 UTC, closed without merging