Update test_turn_on_off_psu_and_check_psustatus to handle PSUs with multiple PDUs
sonic-net/sonic-mgmt pull request #15981
Opened 2024-12-10 14:11 UTC by Javier-Tan

### Description of PR

Summary:
Update test_turn_on_off_psu_and_check_psustatus to handle PSUs with multiple PDUs correctly
Related: #15972

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

### Approach
* Instead of toggling one outlet/PDU, toggle a set at a time connected to one PSU
* Move common PSU helpers function to new psu_helpers.py in tests/common/helpers folder
* Add try / catch block to ensure all PSUs are turned back on after the test
#### What is the motivation for this PR?
Prevent test from failing when toggling a PDU connected to a PSU that will stay on due to other redundant PDUs that were not toggled.
#### How did you do it?
Break PDUs into sets based on PSU, make sure to toggle whole sets at once.
#### How did you verify/test it?
TBC
#### Any platform specific information?
N/A
#### Supported testbed topology if it's a new test case?
N/A
### Documentation

N/A

2024-12-10 23:18 UTC, cyw233 requested changes

2024-12-10 23:18 UTC, cyw233 commented on tests/platform_tests/test_platform_info.py
> +            breakpoint()
Let's remove this `breakpoint()` here 😸

2024-12-10 23:25 UTC, Javier-Tan commented on tests/platform_tests/test_platform_info.py
> +            breakpoint()
Removed, please check :)

2024-12-11 00:15 UTC, Javier-Tan commented
Merging this PR with https://github.com/sonic-net/sonic-mgmt/pull/15972 for simplicities sake

2024-12-11 00:15 UTC, closed without merging