Adding changes to accommodate new snappi model
sonic-net/sonic-mgmt pull request #16148
Opened 2024-12-18 18:14 UTC by selldinesh

### Description of PR

Summary:The apis for traffic and capture operations have been chnaged in the latest snappi model, this PR accommodates those changes
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### Approach
#### What is the motivation for this PR?

#### How did you do it?
Modified traffic and capture related apis to the new snappi model
#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2024-12-18 23:23 UTC, sdszhang commented
Please add a README for the steps, and requried Ixnetwork version. 

@developfast can you review?

2024-12-19 04:12 UTC, developfast commented
Which version is this?

2024-12-19 04:15 UTC, developfast requested changes
putting a hold on this as it may break our internal testing - to verify which version of snappi this is

2025-03-05 23:13 UTC, sdszhang commented
> putting a hold on this as it may break our internal testing - to verify which version of snappi this is

Hi @developfast , how do we procced further on this?

2025-03-20 00:02 UTC, sdszhang commented
@selldinesh can you clarify which snappi version this PR is using? and share the test result?

2025-04-09 23:17 UTC, sdszhang commented
close as new PR #17914 is in place.

2025-04-09 23:17 UTC, closed without merging