Check operational status of ports on fanout when we bring up ports on DUT as part of VoQ link flap tests
sonic-net/sonic-mgmt pull request #4951
Opened 2022-01-14 18:48 UTC by sanmalho-git

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### Approach
#### What is the motivation for this PR?
In VoQ tests against a T2 VoQ chassis we sometimes see 5-6 seconds delay before which the ping to the neighbor works after the port on the DUT is brought up as part of the voq link flap tests.

Currently, when we bring the link up on either the DUT or the fanout, we would only check if the link is up on the DUT.

What we see is that even though the DUT becomes operationally up, the remote peer doesn't become operationally up right away at the same time. It seems to take 2-6 seconds more than the DUT port. If the port is not up on the fanout, then the packets from the DUT is not forwarded to the testbed server, and thus the ping fails.

#### How did you do it?
Fix is to check the link status on the fanout port as well, whenever we bring a port up.

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-10-27 18:54 UTC, tjchadaga commented
/azp run

2022-10-27 18:55 UTC, tjchadaga commented
/easycla

2023-01-27 00:25 UTC, rlhui commented
@wenyiz2021 - please help review/merge this PR?  Thanks.

2023-01-27 01:13 UTC, wenyiz2021 commented
/azp run

2023-01-27 01:14 UTC, wenyiz2021 approved these changes

2023-01-27 01:14 UTC, wenyiz2021 commented
LGTM, need to wait for all PR checks to pass

2023-01-27 01:20 UTC, wenyiz2021 commented
@sanmalho-git can you please change the function name of `def check_intf_link_state`, also add a definition in eos.py?
sth like:

def check_link_oper_status(self, interface_name):
        show_int_result = self.eos_command(
            commands=['show interface %s' % interface_name])
        if 'disabled' in show_int_result['stdout_lines'][0]:
            return False
        return True

2023-01-27 17:49 UTC, wenyiz2021 requested changes
please resolve PR check failure

2023-03-01 18:54 UTC, abdosi commented
cc @gechiang

2023-04-05 21:13 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/devices/sonic.py:1268:59: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:29:1: F401 'tests.common.fixtures.ptfhost_utils.copy_ptftests_directory' imported but unused<br/>tests/voq/test_voq_nbr.py:766:121: E501 line too long (121 > 120 characters)<br/>tests/voq/test_voq_nbr.py:811:1: E303 too many blank lines (3)<br/>tests/voq/test_voq_nbr.py:830:32: E211 whitespace before '('<br/>tests/voq/test_voq_nbr.py:916:40: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:916:42: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:916:44: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:954:121: E501 line too long (133 > 120 characters)<br/>tests/voq/test_voq_nbr.py:1015:25: E128 continuation line under-indented for visual indent<br/>tests/voq/test_voq_nbr.py:1019:121: E501 line too long (132 > 120 characters)<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2023-04-05 23:15 UTC, wenyiz2021 commented
> @sanmalho-git can you please change the function name of `def check_intf_link_state`, also add a definition in eos.py? sth like:
> 
> ```
> def check_link_oper_status(self, interface_name):
>         show_int_result = self.eos_command(
>             commands=['show interface %s' % interface_name])
>         if 'disabled' in show_int_result['stdout_lines'][0]:
>             return False
>         return True
> ```

@sanmalho-git reason I ask is current `check_intf_link_state` in eos.py is not checking oper status, it returns True if either oper OR admin status is up, would be good to rename the function and implement the same in eos.py, to check only oper status

2023-04-05 23:24 UTC, wenyiz2021 commented
eos output:
```
#show int Et1
Ethernet1 is up, line protocol is up (connected)
  Hardware is Ethernet, address is 001c.73f5.ea78 (bia 001c.73f5.ea78)
```

2023-04-05 23:25 UTC, mssonicbld commented
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/devices/sonic.py:1268:59: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:29:1: F401 'tests.common.fixtures.ptfhost_utils.copy_ptftests_directory' imported but unused<br/>tests/voq/test_voq_nbr.py:766:121: E501 line too long (121 > 120 characters)<br/>tests/voq/test_voq_nbr.py:811:1: E303 too many blank lines (3)<br/>tests/voq/test_voq_nbr.py:830:32: E211 whitespace before '('<br/>tests/voq/test_voq_nbr.py:916:40: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:916:42: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:916:44: E231 missing whitespace after ','<br/>tests/voq/test_voq_nbr.py:954:121: E501 line too long (133 > 120 characters)<br/>tests/voq/test_voq_nbr.py:1015:25: E128 continuation line under-indented for visual indent<br/>tests/voq/test_voq_nbr.py:1019:121: E501 line too long (132 > 120 characters)<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

2023-04-05 23:35 UTC, wenyiz2021 commented
@sanmalho-git suggest to change your added function name to `check_link_oper_status` to not confuse future usage

2023-04-06 00:34 UTC, wenyiz2021 commented on tests/common/devices/eos.py
>      def check_intf_link_state(self, interface_name):
the main issue I think is this function checks for admin status, not oper status you are looking for.

```
#show int status
Port       Name                                          Status       Vlan     Duplex  Speed    Type                     Flags Encapsulation
Et1        xxx-Ethernet1/1                        connected    2461     full         40G    40GBASE-CR4                    
 
#show int Et1
Ethernet1 is up, line protocol is up (connected)
```

2023-05-31 16:50 UTC, mlok-nokia commented
@mannytaheri  Please take a look at this issue

2023-07-26 16:16 UTC, mlok-nokia commented
This PR has been replaced by multiple PRs.  It should be closed or ignored.

2023-07-26 18:24 UTC, wenyiz2021 commented
closing this PR as https://github.com/sonic-net/sonic-mgmt/pull/8468 with same content was merged.
There is hidden issue in eos fanout, PR wants to check oper status, but in the function defined in eos.py, it checks for admin status. I will raise another PR to fix this

2023-07-26 18:24 UTC, closed without merging