[MASIC] test_bgp_update_timer to support for multi-asic
sonic-net/sonic-mgmt pull request #5978
Opened 2022-07-13 23:11 UTC by wenyiz2021

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-07-22 03:55 UTC, lolyu commented
/azp run

2022-07-22 03:56 UTC, lolyu requested changes
1. Please fill out the pull request description as expected.
2. Please add your signature to commits.

2022-07-25 02:33 UTC, lolyu reviewed
Please, use `git commit -s` to add your signature to the commit.

2022-08-08 17:32 UTC, wenyiz2021 commented
/easycla

2022-09-14 16:04 UTC, mannytaheri commented
Default timeout_s is set to 30 seconds in wait_tcp_connection(client, server_hostname, listening_port, timeout_s = 30).
However 30 seconds may be not enough for BGP to  establish.  We need to increase timeout_s to 60 seconds.

Please add timeout_s=60 in wait_tcp_connection(client, server_hostname, listening_port) on line 78 of tests.common.helpers.bgp.py:
if not wait_tcp_connection(self.ptfhost, self.ptfip, self.port, timeout_s=60):
    raise RuntimeError("Failed to start BGP neighbor %s" % self.name)

We had to do similar thing in  PR #6206:
- pt_assert(wait_tcp_connection(localhost, ptfhost.mgmt_ip, BGP_MONITOR_PORT),
+ pt_assert(wait_tcp_connection(localhost, ptfhost.mgmt_ip, BGP_MONITOR_PORT, timeout_s=60),

2022-09-14 16:31 UTC, mannytaheri commented
n0.stop_session() and n1.stop_session() on lines 287 and 288 of test_bgp_update_timer do not delete the BGP sessions since stop_session() is not multi asics aware.
These are the commands which do not delete the BGP sessions:
redis-cli -n 4 -c DEL 'BGP_NEIGHBOR|20.0.0.1'
redis-cli -n 4 -c DEL 'DEVICE_NEIGHBOR_METADATA|pseudoswitch0'

2022-09-14 17:20 UTC, wenyiz2021 commented
> n0.stop_session() and n1.stop_session() on lines 287 and 288 of test_bgp_update_timer do not delete the BGP sessions since stop_session() is not multi asics aware. These are the commands which do not delete the BGP sessions: redis-cli -n 4 -c DEL 'BGP_NEIGHBOR|20.0.0.1' redis-cli -n 4 -c DEL 'DEVICE_NEIGHBOR_METADATA|pseudoswitch0'

@mannytaheri thanks for the review.
why doesn't the 2 commands delete correct BGP sessions? they don't need to be multi-asic aware, as long as the session ip/name is given to stop_session(), no?

2022-09-27 18:55 UTC, closed without merging