[doc] Add M0 topo description to testbed overview doc
sonic-net/sonic-mgmt pull request #6229
Opened 2022-08-26 04:18 UTC by yaqiangz

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### Approach
#### What is the motivation for this PR?
Describe details of M0 type topology.

#### How did you do it?
This added document explaining M0 topology.

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-08-26 11:33 UTC, Blueve requested changes

2022-08-26 11:33 UTC, Blueve commented on docs/testbed/README.testbed.Overview.md
> +The M0 type topology is to simulate a SONiC DUT running as a M0 device. For this type of topology, a set of DUT ports are connected to VMs simulating upstream M1 neighbors. Another set of the ports a
...running as a `Management ToR Router` ... simulating upstream M1`(Management Leaf Router)` neighbors ... simulating downstream Mx`(BMC Management Router)` neighbors.

2022-08-26 11:33 UTC, Blueve commented on docs/testbed/README.testbed.Overview.md
> +* The last 2 ports are connected to another 2 VMs simulating downstream Mx neighbors. No port-channel is configured for the links between DUT and Mx neighbors.
Why no port-channel?

2022-08-30 05:32 UTC, Blueve commented on docs/testbed/README.testbed.Overview.md
> +* The next 4 ports are connected to 4 VMs simulating M1 devices. The connection to each of the upstream M1 is configured as a port-channel with single link.
1. next 2 ports -> Mx
2. last 4 ports -> M1

2022-08-31 05:24 UTC, yaqiangz commented on docs/testbed/README.testbed.Overview.md
> +* The next 4 ports are connected to 4 VMs simulating M1 devices. The connection to each of the upstream M1 is configured as a port-channel with single link.
Fixed

2022-08-31 06:12 UTC, Blueve approved these changes

2022-09-01 01:55 UTC, yaqiangz commented
/azp run

2022-09-01 05:32 UTC, merged