Fix verify_no_packet_any call in fib_test
sonic-net/sonic-mgmt pull request #6461
Opened 2022-10-04 12:20 UTC by AndriiLozovyi

Signed-off-by: Andrii-Yosafat Lozovyi <andrii-yosafatx.lozovyi@intel.com>

### Description of PR

Summary: The verify_no_packet_any() returns nothing. This PR fixes verify_no_packet_any() call in fib_test.py to avoid the failure in case of no packets expected (drop action) in FIB TC:
```
    "stderr_lines": [
        "WARNING: No route found for IPv6 destination :: (no default route?)", 
        "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.", 
        "  from cryptography.hazmat.backends import default_backend", 
        "vrf_test.FwdTest ... ERROR", 
        "", 
        "======================================================================", 
        "ERROR: vrf_test.FwdTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"ptftests/vrf_test.py\", line 98, in runTest", 
        "    self.check_fwd_entries()", 
        "  File \"ptftests/vrf_test.py\", line 87, in check_fwd_entries", 
        "    self.check_ip_range(ip_range, next_hop, ipv4)", 
        "  File \"ptftests/fib_test.py\", line 222, in check_ip_range", 
        "    self.check_ip_route(src_port, dst_ip, exp_port_lists, ipv4)", 
        "  File \"ptftests/fib_test.py\", line 265, in check_ip_route", 
        "    res = self.check_ipv4_route(src_port, dst_ip_addr, dst_port_lists)", 
        "  File \"ptftests/fib_test.py\", line 368, in check_ipv4_route", 
        "    rcvd_port_index, rcvd_pkt = verify_no_packet_any(self, masked_exp_pkt, dst_ports)", 
        "TypeError: 'NoneType' object is not iterable", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 0.122s", 
        "", 
        "FAILED (errors=1)"
    ], 
```

Fixes #6460

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?
Fix Vrf test cases
#### How did you do it?

#### How did you verify/test it?
Run `vrf/test_vrf.py::TestVrfIsolation`

#### Any platform specific information?
```
SONiC Software Version: SONiC.master.154150-dirty-20220928.095407
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: f890606d8
Build date: Wed Sep 28 16:09:31 UTC 2022
Built by: AzDevOps@sonic-build-workers-0025UB
Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
```
#### Supported testbed topology if it's a new test case?

### Documentation

2022-10-13 13:35 UTC, SavchukRomanLv submitted a review, later dismissed

2022-11-08 02:27 UTC, wangxin approved these changes

2022-11-08 02:32 UTC, wangxin commented on ansible/roles/test/files/ptftests/fib_test.py
> +            return None
Is `return (None, None)` better? This won't break the type of return value.

2022-11-08 02:33 UTC, wangxin requested changes
I have a concern with updating the return value type to single `None`.

2022-11-09 09:00 UTC, AndriiLozovyi commented
> I have a concern with updating the return value type to single `None`.

Updated return value to `return (None, None)`

2022-11-09 12:24 UTC, ZhaohuiS approved these changes
LGTM

2022-11-09 13:25 UTC, ZhaohuiS commented
/azp run

2022-11-20 03:00 UTC, wangxin approved these changes

2022-11-20 03:02 UTC, merged