Ignore echo_receive related ERR log for now
sonic-net/sonic-mgmt pull request #6501
Opened 2022-10-10 10:33 UTC by ZhaohuiS

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?
Currently, there is an issue for echo_receive related ERR log, issue https://github.com/sonic-net/sonic-buildimage/issues/12303.
test_lag_2 failed at teardown loganalyzer because this ERR log, ignore it for now, when the issue is fixed, will remove these two ignore ERRs.

#### How did you do it?
Add below ERR log into `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt`
```
r, ".* ERR python3: :- echo_receive: failing to read echo rc.*"
r, ".* ERR python3: :- echo_receive: last:errno=.*"
```
#### How did you verify/test it?
Run `pc.test_lag_2.py`

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-10-10 14:53 UTC, StormLiangMS approved these changes
LGTM

2022-10-11 02:08 UTC, dgsudharsan commented
Hi. These errors are also seen in orchagent. Should the ignore include these too?

Oct 11 03:42:37.988129 r-panther-19 ERR swss#orchagent: :- echo_receive: failing to read echo rc=11

Oct 11 03:42:37.988201 r-panther-19 ERR swss#orchagent: :- echo_receive: last:errno=11

2022-10-11 02:11 UTC, dgsudharsan requested changes
Please check if this error log needs to be further generalized to include orchagent case. We may need to remove python3 fro pattern

Oct 11 03:42:37.988201 r-panther-19 ERR swss#orchagent: :- echo_receive: last:errno=11

2022-10-11 03:04 UTC, ZhaohuiS commented
> Please check if this error log needs to be further generalized to include orchagent case. We may need to remove python3 fro pattern
> 
> Oct 11 03:42:37.988201 r-panther-19 ERR swss#orchagent: :- echo_receive: last:errno=11

@dgsudharsan Thank you for your comment, I updated code, could you please help with review? Thanks.

2022-10-13 09:02 UTC, ZhaohuiS commented
/azp run

2022-10-14 16:27 UTC, dgsudharsan submitted a review, later dismissed

2022-10-15 08:59 UTC, XuChen-MSFT approved these changes

2022-10-15 15:41 UTC, XuChen-MSFT approved these changes

2022-10-16 06:46 UTC, merged