[runtime] improve runtime of tests
sonic-net/sonic-mgmt pull request #6873
Opened 2022-11-22 15:57 UTC by AntonHryshchuk

Signed-off-by: Anton <antonh@nvidia.com>

### Description of PR

Summary:
Improve runtime of tests. The update of the asic service related to multi-devices only. 
Fixes #6872

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

### Approach
#### What is the motivation for this PR?
short runtime of tests

#### How did you do it?
added "if" condition before removing service from DEFAULT_ASIC_SERVICES

#### How did you verify/test it?
executed and compared the runtime before and after the change

2022-11-22 15:59 UTC, AntonHryshchuk commented
@abdosi please review

2022-11-28 16:22 UTC, liat-grozovik commented
@abdosi LGTM but appreciate to get your feedback as it seems related to https://github.com/sonic-net/sonic-mgmt/pull/6751 
To me the fix seems crucial as it causing a degradation in single ASIC switch. Please prioritize the review.

2022-11-28 18:20 UTC, abdosi commented on tests/common/devices/multi_asic.py
> +        if self.sonichost.is_multi_asic:
can we make it `is_supervisor_node()` that should be better.

2022-11-28 18:20 UTC, abdosi requested changes
as noted.

2022-12-01 13:51 UTC, liat-grozovik commented
@abdosi  could you please approve following the fix provided?

2022-12-06 09:45 UTC, liat-grozovik commented
> as noted.

comment was addressed. moving a head with merge

2022-12-07 10:21 UTC, roysr-nv approved these changes

2022-12-09 22:02 UTC, abdosi approved these changes

2022-12-09 22:02 UTC, merged