Skipping reboot on Supervisor for Cisco 8000 distributed chassis
sonic-net/sonic-mgmt pull request #6991
Opened 2022-12-08 04:05 UTC by vperumal

### Description of PR
Skipping reboot on Supervisor for Cisco 8000 distributed chassis. 

Summary:
Fixes # (issue)

### Type of change

- Fill x for your type of change.
- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

### Approach
#### What is the motivation for this PR?
Currently we are hitting an intermittent issue if Supervisor is rebooted during a test. To avoid tests to get errored out during nightly run, we are skipping reboot for supervisor node

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2022-12-09 02:14 UTC, SuvarnaMeenakshi commented
Can we add the test cases to be skipped here: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.
We could open a github issue and add that under condition along with platform string of supervisor.

2022-12-09 02:18 UTC, vperumal commented
> Can we add the test cases to be skipped here: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.
> We could open a github issue and add that under condition along with platform string of supervisor.

Hi @SuvarnaMeenakshi, the check for skip using test_mark_conditions happens at the start of the script even before dut is selected. It works fine in a single dut case but in case of multi-dut wherein it is randomly picked up within the testcase, test_mark_conditions does not work. Hence had to put it in each individual testcase.

2022-12-15 03:14 UTC, vperumal commented
@abdosi , added skip for watchdog reboot here - since I closed - https://github.com/sonic-net/sonic-mgmt/pull/6812.

2023-01-04 20:42 UTC, abdosi requested changes
please add close pid platforms also.

2023-01-11 01:23 UTC, abdosi commented on tests/acl/test_acl.py
> +            pytest.skip("Skip reboot for Supervisor card in Cisco 8000 distributed chassis")
Remove this .  this should not get call for supervisor.

2023-03-06 19:17 UTC, abdosi commented
we will not need now as reboot is working fine

2023-03-06 19:17 UTC, closed without merging