[Snappi] Modifications to pfcwd a2a test design for mlnx 4600c
sonic-net/sonic-mgmt pull request #7367
Opened 2023-01-31 20:11 UTC by developfast

### Description of PR

Summary: The Mellanox 4600c switch does not drop packets on the Rx port when a PFC storm is generated on a port, thereby triggering the PFC watch dog. The existing pfcwd a2a (all-to-all) test assumed that packets would be dropped on the Rx port, regardless of switch HwSKU. This change modifies how the test will verify the flow of packets for the Mellanox 4600c during a PFCWD all-to-all test. 

Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?
Pfcwd a2a test failure on mellanox 4600c switch. 

#### How did you do it?
Added a condition that checks for whether the switch is a mellanox 4600c switch, and have a check to ensure that no packets are dropped on the Rx port. 

#### How did you verify/test it?
Ran the test on the mellanox 4600c - it passed. 

#### Any platform specific information?
Platform - x86_64-mlnx_msn4600c-r0

#### Supported testbed topology if it's a new test case?

### Documentation

2023-01-31 20:12 UTC, developfast commented
@baiwei0427 please review

2023-01-31 20:16 UTC, baiwei0427 requested changes

2023-01-31 20:16 UTC, baiwei0427 commented on tests/snappi/pfcwd/files/pfcwd_multi_node_helper.py
> +                     is_mlnx_4600c=is_mlnx_4600c)
It seems to me that we should pass 'platform' rather than 'is_mlnx_4600c' as an argument to verify_results.

2023-02-01 04:22 UTC, baiwei0427 approved these changes

2023-02-03 17:52 UTC, neethajohn commented on tests/snappi/pfcwd/files/pfcwd_multi_node_helper.py
> +    platform = duthost.facts['platform']
please get the asic_type instead of platform. All mellanox devices have this behavior

2023-02-03 17:53 UTC, neethajohn commented
@developfast, please modify all the other pfcwd snappi testcases as well for mellanox platform to exclude the rx drop check

2023-02-21 19:22 UTC, baiwei0427 approved these changes

2023-02-24 17:43 UTC, neethajohn approved these changes

2023-02-24 21:43 UTC, merged