[DualTor][Mellanox] Skip dualtor test_downstream_ecmp_nexthops test on Mellanox 2700 platform
sonic-net/sonic-mgmt pull request #7785
Opened 2023-03-20 03:19 UTC by congh-nvidia

### Description of PR

Summary:
On Mellanox 2700 platform, due to HW limitation, the hierarchy ecmp(re-hash) behaviour is not as expected in the dualtor test test_downstream_ecmp_nexthops. 
### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

### Approach
#### What is the motivation for this PR?
Skip dualtor test_downstream_ecmp_nexthops test on Mellanox 2700 platform
#### How did you do it?
Add the skip in tests_mark_conditions.yaml
#### How did you verify/test it?
By automation.
#### Any platform specific information?
Only for Mellanox 2700 platform
#### Supported testbed topology if it's a new test case?

### Documentation

2023-03-21 17:08 UTC, liat-grozovik requested changes
skip should be for all Spectrum platforms

2023-03-21 17:09 UTC, liat-grozovik commented
@congh-nvidia  i changed the subject as the description.
the skip should be only spectrum platform while it can run on other spectrum-2 + platforms.

2023-03-22 03:48 UTC, congh-nvidia commented
> @congh-nvidia i changed the subject as the description. the skip should be only spectrum platform while it can run on other spectrum-2 + platforms.

Hi @liat-grozovik , I've updated the skip condition and the description, please check.

2023-03-31 10:21 UTC, nhe-NV approved these changes

2023-04-09 09:16 UTC, liat-grozovik approved these changes

2023-04-09 09:16 UTC, merged

2023-04-09 09:16 UTC, liat-grozovik commented
@bingwang-ms FYI