Added multi dut PFC lossy test case
sonic-net/sonic-mgmt pull request #7913
Opened 2023-03-29 23:19 UTC by vikumarks

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2023-04-19 17:51 UTC, kamalsahu0001 commented
Testplan for PFC Lossy testcase is same for both singledut and multidut
https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/pfc/PFC_PAUSE_LOSSY_README.md

2023-08-14 04:04 UTC, developfast commented
@vikumarks We've recently implemented updates to the Snappi tests, relocating all test cases to the following location: https://github.com/sonic-net/sonic-mgmt/tree/master/tests/snappi_tests. Kindly make the necessary adjustments to reflect this change.

Furthermore, I kindly request you take a look at the pull request at https://github.com/sonic-net/sonic-mgmt/pull/8660. Please ensure that the PFC tests for multi DUT environments align harmoniously with the existing PFC tests that have been refactored.

2023-08-18 16:46 UTC, developfast commented
Please add the appropriate new parameters added to this PR to `snappi_test_params`.

2023-08-20 18:58 UTC, developfast requested changes
@vikumarks Can you address the pre-commit failures? One more thing, for these multidut cases, can you move them to a multidut folder inside the snappi_tests directory? For instance, for pfc multidut cases, can you put it in a folder like `tests/snappi_tests/multidut/pfc/...`? This is to make organisation easier when we are running these tests on our nightly testbeds.

2023-08-20 19:04 UTC, developfast commented
Can you list all dependent PRs i.e. PR numbers with a # for this PR to be merged? This will make tracking easier

2023-08-23 23:48 UTC, vikumarks commented
> Please add the appropriate new parameters added to this PR to `snappi_test_params`.
@developfast , Params are part of PR #8186

2023-08-23 23:49 UTC, vikumarks commented
> @vikumarks Can you address the pre-commit failures? One more thing, for these multidut cases, can you move them to a multidut folder inside the snappi_tests directory? For instance, for pfc multidut cases, can you put it in a folder like `tests/snappi_tests/multidut/pfc/...`? This is to make organisation easier when we are running these tests on our nightly testbeds.

@developfast, moved the cases to multidut folder

2023-12-13 23:56 UTC, vmittal-msft approved these changes
Looks ok to me. Can you please add more comments to make code more readable? Also, please share test results and SW version details.

@baiwei0427 @developfast please see if this looks ok.

2023-12-14 01:51 UTC, wenyiz2021 commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
should this be >= 2?

2023-12-14 01:51 UTC, wenyiz2021 commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
same here?

2023-12-14 01:51 UTC, wenyiz2021 commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
same here

2023-12-14 01:52 UTC, wenyiz2021 commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
same here

2023-12-14 01:53 UTC, wenyiz2021 requested changes
please see my comments

2023-12-14 12:20 UTC, developfast requested changes

2023-12-19 17:42 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
Fixed

2023-12-19 17:42 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
Fixed

2023-12-19 17:42 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
Fixed

2023-12-19 17:43 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +    if (len(linecard_configuration_set[line_card_choice]['hostname']) == 2):
Fixed

2023-12-19 17:43 UTC, vikumarks commented on tests/snappi_tests/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +pytestmark = [pytest.mark.topology('snappi')]
Fixed

2023-12-19 17:43 UTC, vikumarks commented on tests/snappi_tests/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +                                     ):
Fixed

2023-12-21 06:31 UTC, vmittal-msft commented
@vikumarks please take care of comments. @baiwei0427  @developfast  is this ok to merge ?

2024-01-09 03:31 UTC, developfast requested changes
All plain `assert` cases need to be changed to either `pytest_assert` or `pytest_require`

2024-01-22 19:41 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +        dut_list = [dut for dut in duthosts if linecard_configuration_set[line_card_choice]['hostname'] == [dut.hostname]]  # noqa: E501
Fixed

2024-01-22 19:42 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +        assert False, "Invalid line_card_choice value passed in parameter"
Fixed

2024-01-22 19:42 UTC, vikumarks commented on tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
> +        assert False, "Hostname can't be an empty list"
Fixed

2024-02-02 00:16 UTC, vmittal-msft commented
@developfast please approve if ok to merge.

2024-02-02 17:19 UTC, developfast approved these changes
lgtm

2024-02-02 17:19 UTC, developfast commented
@yxieca can you pls help merge?

2024-02-02 17:23 UTC, yxieca commented
@vikumarks can you fill the PR template "how did you do it" section with a brief description of the fix?

2024-02-14 00:24 UTC, vikumarks commented
@yxieca Filled the missing "how did you do it" section

2024-02-14 18:27 UTC, yxieca commented
@wenyiz2021 please assess if the issue you raised had been addressed?

2024-02-15 16:52 UTC, vikumarks commented
> @yxieca Filled the missing "how did you do it" section

PR Template has been completed as requested , Please merge.

2024-02-22 19:39 UTC, judyjoseph approved these changes

2024-02-26 18:26 UTC, vikumarks commented
@yxieca can you please merge this PR

2024-02-26 21:52 UTC, merged

2024-02-28 04:26 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/11792

2024-02-28 04:26 UTC, mssonicbld commented
Cherry-pick PR to 202205: https://github.com/sonic-net/sonic-mgmt/pull/11793

2024-02-28 04:26 UTC, mssonicbld commented
Cherry-pick PR to 202311: https://github.com/sonic-net/sonic-mgmt/pull/11794

2024-03-04 18:33 UTC, wenyiz2021 reviewed
LGTM