Added multi dut ecn red accuracy test case
sonic-net/sonic-mgmt pull request #7915
Opened 2023-03-29 23:37 UTC by vikumarks

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2023-04-19 17:53 UTC, kamalsahu0001 commented
Testplan for ECN red accuracy is same for both singledut and multidut
https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/ecn/ECN_ACCURACY_README.md

2023-10-06 16:31 UTC, dks0692 commented
@developfast Can you please review

2024-02-28 22:11 UTC, vmittal-msft approved these changes
This seems to be dependent on https://github.com/sonic-net/sonic-mgmt/pull/7914. Also, could we verify on single dut-single asic, single dut-multi asic, multi dut ? Please paste results here. Also, when the test is run, is it going to verify all these combinations or going to randonly pick one out of 3 ?

2024-03-05 21:30 UTC, vmittal-msft commented
@vikumarks please fix failures. 
@yxieca @wangxin please help merge this.

2024-03-07 20:24 UTC, developfast requested changes
as comments

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    skip_ecn_tests(duthost1)
put maybe on the same line as a `or` case. This test cannot possibly run if either doesn't meet the criteria.

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # logger.info(tabulate(output_table, headers=['Queue Length', 'ECN Marking Probability']))
remove this comment or log it?

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # Dump queue length vs. ECN marking probability into logger file """
Remove the """ at the end

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +        # Check if we capture all the packets in each round """
Remove the """ at the end

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # Check if we capture packets of all the rounds """
Remove the """ at the end

2024-03-07 20:24 UTC, developfast commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # logger.info(tabulate(output_table, headers=['Queue Length', 'ECN Marking Probability']))
Recommend logging it

2024-03-07 20:25 UTC, developfast commented
@vikumarks can you pls check the test error?

2024-03-07 20:38 UTC, vikumarks commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # Check if we capture packets of all the rounds """
Fixed

2024-03-07 20:38 UTC, vikumarks commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +        # Check if we capture all the packets in each round """
Fixed

2024-03-07 20:38 UTC, vikumarks commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # Dump queue length vs. ECN marking probability into logger file """
Fixed

2024-03-07 20:38 UTC, vikumarks commented on tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
> +    # logger.info(tabulate(output_table, headers=['Queue Length', 'ECN Marking Probability']))
Fixed

2024-03-07 20:40 UTC, vikumarks commented
> @vikumarks can you pls check the test error?

@developfast This PR depends on PR7914  for multidut_helper.py file.

2024-03-13 19:15 UTC, vikumarks commented
@developfast can we merge this PR

2024-03-19 23:54 UTC, vmittal-msft commented
@vikumarks it is failing in test. please check.

@yxieca @developfast @wangxin please help merge.

2024-03-22 16:29 UTC, vikumarks commented
> @vikumarks it is failing in test. please check.
> 
> @yxieca @developfast @wangxin please help merge.

@vmittal-msft All checks have passed 
@yxieca @developfast @wangxin  please help merge

2024-03-25 19:13 UTC, vmittal-msft commented
@yxieca @wangxin please help

2024-03-25 19:26 UTC, developfast approved these changes
lgtm

2024-03-26 16:57 UTC, merged