cisco-8000: Fix keyError from Qos param generator
sonic-net/sonic-mgmt pull request #8289
Opened 2023-05-12 03:35 UTC by rraghav-cisco

In the cisco qos_param generator we have:
            self.qos_params["shared_res_size_1"].update(res_1)
            self.qos_params["shared_res_size_2"].update(res_2)

When the qos yaml file doesn't have the 2 keys shared_res_size_1 and 2, the above code fails. This PR is to fix this.

2023-05-17 00:45 UTC, abdosi commented
please target to master branch. validation can be on 202205 branch.

2023-05-17 00:45 UTC, abdosi requested changes
as comment

2023-05-18 23:34 UTC, abdosi approved these changes

2023-05-18 23:35 UTC, merged

2023-08-09 04:35 UTC, XuChen-MSFT commented
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis