cisco: multi-asic qos-sai: Adding fixes to pass lossless Voq after multi-asic support is available in qos-sai.
sonic-net/sonic-mgmt pull request #8304
Opened 2023-05-14 03:57 UTC by rraghav-cisco

Modifications:
1. Updated the LosslessVoq test to use the newly available fixures instead of the previous ones. The new fixure provides the source and destination DUTs, Asics seperately.
2. Updated the losslessvoq test in PTF to support the new parameters.
3. Also modified the PTF script to use a new function that makes sure that the packets go to the given destination port. This allows more reliable way of testing lossless voq.
4. Modified the fill_leakout_plus_one to assert internally rather than returning False. All the callers are not needed to assert anymore.

2023-05-14 03:59 UTC, rraghav-cisco commented
@rbpittman , @abdosi , @vmittal-msft : Pls review.

2023-05-14 03:59 UTC, rraghav-cisco commented
The following is the result from running a single-asic mode only:
----------------------------------------------------------------------------- generated xml file: /run_logs/qos-rerun/qos/test_qos_sai.py::TestQosSai::testQosSaiLosslessVoq.xml -----------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------------------------------------------------
03:04:08 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================================= 4 passed in 760.90 seconds =================================================================================================================
sonic@e70a4c3cc9f8:/masic/tests$ 
sonic@e70a4c3cc9f8:/masic/tests$

2023-05-17 00:49 UTC, abdosi commented
need to be on master. validation can be on 202205.

2023-05-17 00:49 UTC, abdosi requested changes
as comment

2023-05-17 19:45 UTC, rraghav-cisco commented
> need to be on master. validation can be on 202205.

The adjustments to this test were needed because of the multi-asic code. But a piece of the PR doesn't depend on the multi-asic PR. I can try to port that part to master at the moment, pls let me know.

2023-05-17 21:04 UTC, rbpittman commented
I didn't realize the multi-asic code was in only 202205, causing a significant divergence between the master branch and the 202205 branch. 
In that case, I'd suggest the redirection to master should wait until master gets updated to where 202205 is. That way there's little or no conflicts.

2023-05-17 23:27 UTC, abdosi approved these changes
Please make sure we port this to master. Create github tracker for same.

2023-05-17 23:27 UTC, abdosi commented
please rebase with latest 202205.

2023-05-18 23:42 UTC, abdosi commented on tests/saitests/py3/sai_qos_tests.py
> +    def get_rx_port_udp(dp, src_port_id, pkt, exp_pkt):
@rraghav-cisco please make in master PR for this we update `get_rx_port` function accordingly.

2023-05-18 23:45 UTC, merged

2023-08-09 04:41 UTC, XuChen-MSFT commented
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis