cisco: qos-sai: multiasic: Adding adjustments for xon and a few other testcases
sonic-net/sonic-mgmt pull request #8500
Opened 2023-06-06 05:15 UTC by rraghav-cisco

This PR is to fix the issues we have seen in multi-asic runs (source and dest are different asics, same DUT or different DUTs). The PR has:
1. Adjustments to PFCXon testcase, along with qos.yaml file values for topo-t2 for PFCXon testcase.

2023-06-06 18:51 UTC, abdosi commented
Please add py-test result for xon test case
Please remove point (3) in above PR description

2023-06-08 15:05 UTC, rraghav-cisco commented
[xon.tar.gz](https://github.com/sonic-net/sonic-mgmt/files/11689929/xon.tar.gz)

Attaching the log for Xon.

2023-06-08 16:33 UTC, XuChen-MSFT commented on tests/qos/test_qos_sai.py
> +
this change is not necessary in function.
and it will cause conflict with changes in PR https://github.com/sonic-net/sonic-mgmt/pull/8480

2023-06-08 16:37 UTC, XuChen-MSFT commented on tests/qos/test_qos_sai.py
> +            if not get_src_dst_asic_and_duts['single_asic_test'] and \
this change has already included in PR https://github.com/sonic-net/sonic-mgmt/pull/8480

2023-06-08 21:34 UTC, abdosi commented on tests/qos/qos_sai_base.py
> +            "single_asic_test": (src_dut == dst_dut and
yes, we will merge PR# 8480 first so this will not be there.

2023-06-08 22:04 UTC, abdosi approved these changes

2023-06-08 22:05 UTC, abdosi commented
Please check this comment `Skip PG Shared Watermark for Lossy Traffic for multi-asic/multi-dut scenario of T2. Single asic will be still validated.`. is it still applicable? ?

2023-06-09 00:01 UTC, XuChen-MSFT commented on tests/qos/files/qos.yml
> +                 xon_1:
indent issue, will cause yaml parser failure

2023-06-09 00:26 UTC, XuChen-MSFT commented on tests/saitests/py3/sai_qos_tests.py
> +        test_case, src_port_id, dst_port_id, pkt, queue, asic_type,
syntax issue

2023-06-09 00:59 UTC, XuChen-MSFT commented on tests/saitests/py3/sai_qos_tests.py
> -                       pkt, int(self.test_params['pg']), asic_type)
======================================================================
ERROR: sai_qos_tests.PFCtest
----------------------------------------------------------------------
Traceback (most recent call last):
  File \"saitests/py3/sai_qos_tests.py\", line 1249, in runTest
    pkt, int(self.test_params['pg']), asic_type, pkts_num_egr_mem)
UnboundLocalError: local variable 'pkts_num_egr_mem' referenced before assignment

2023-06-09 12:23 UTC, XuChen-MSFT commented
As agreed at last weekly meeting,
to better manage PR, recommended to split this change into multiple small PR to merge if possible.

2023-06-13 14:37 UTC, rraghav-cisco commented
> Please check this comment `Skip PG Shared Watermark for Lossy Traffic for multi-asic/multi-dut scenario of T2. Single asic will be still validated.`. is it still applicable? ?

As we discussed, yes, as of now this is valid.

2023-06-14 00:32 UTC, abdosi commented on tests/saitests/py3/sai_qos_tests.py
> +
merge this change with other PR with PG to Dscp mapping

2023-06-14 00:33 UTC, abdosi commented on tests/saitests/py3/switch.py
> +        SAI_INGRESS_PRIORITY_GROUP_STAT_CURR_OCCUPANCY_BYTES
create new PR for this and other new function `fill_egress_plus_one`

2023-06-14 00:35 UTC, abdosi requested changes
as comment

2023-06-20 18:36 UTC, rraghav-cisco commented
> Please add py-test result for xon test case Please remove point (3) in above PR description

This is done. As per our previous discussions, point-3 is still valid, so is being kept as it is.

2023-07-07 18:34 UTC, abdosi commented
@rraghav-cisco please resolve conflict so that we can merge it.

2023-07-07 19:34 UTC, rraghav-cisco commented
> @rraghav-cisco please resolve conflict so that we can merge it.

@abdosi: Resolved the conflicts.

2023-07-08 17:33 UTC, abdosi approved these changes

2023-07-08 17:35 UTC, abdosi commented
@XuChen-MSFT : can you please help with sign-off of this PR. We have divided this PR into multiple PR's (which are already merged)

2023-07-10 03:25 UTC, wangxin commented
@rraghav-cisco Is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?
If it is not backport, then probably we have to fix the issue again in master branch?

2023-07-10 06:01 UTC, rraghav-cisco commented
> @rraghav-cisco Is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description? If it is not backport, then probably we have to fix the issue again in master branch?

Hi @wangxin : No it is a direct fresh PR on 202205. The master branch doesn't have the multi-asic code needed by this PR.

2023-07-12 17:37 UTC, abdosi commented
@wangxin can you please help merge of this.

2023-07-13 02:09 UTC, merged

2023-07-22 00:18 UTC, bingwang-ms commented
@rraghav-cisco We saw regression caused by this PR.
As far as I understand, there may be some issue in function `get_multiple_flows`. In below `while` loop, you are updating the `src_ip` (from `192.0.0.0` to `192.0.0.255`) in each iteration, and expect the egress port to equal with `dst_id`. 
I think that logic is not reliable, cause that highly relys on the hashing algorithm. It's not assured that the packet will finally hit the expected port.
At least on our testbed, we saw the endless loop. 
https://github.com/rraghav-cisco/sonic-mgmt/blob/78baeb6465c9c15c2fa72f184262656f4a4ced37/tests/saitests/py3/sai_qos_tests.py#L169
```
while (num_of_pkts < packets_per_port):
            ip_Addr = next(IP_ADDR)
            pkt_args = {
                'ip_ecn':ecn,
                'ip_ttl':ttl,
                ......
            if get_rx_port_pkt(dp, src_tuple[0], pkt, masked_exp_pkt) == dst_id:
                try:
                    all_pkts[src_tuple[0]].append((pkt, masked_exp_pkt))
                    num_of_pkts+=1
                except KeyError:
                    all_pkts[src_tuple[0]] = []
                    all_pkts[src_tuple[0]].append((pkt, masked_exp_pkt.exp_pkt))
                    num_of_pkts+=1
```
Can you please check and reply? Thanks

2023-07-22 01:07 UTC, rraghav-cisco commented
@bingwang-ms : I understand. When I see endless loop, it only means the dst_port_ip is not directed to the intended dst_port_id at all. That is when we see the infinite loop. It shouldn't happen unless there is a problem in the DUT, or there is a mismatch in the arguments to the ptf call.

I will add a check to stop the infinite loop after 500 ip addresses, if that is ok. If none of the 500 src addresses work(the dst_port_id never got any of the packets, but there is other ports receive all the packets), then this is a problem, and a RuntimeError will be raised.

It will help me if you can provide the topology (t0/t1/t1-lag/t2).

2023-07-24 15:45 UTC, bingwang-ms commented
Thanks @rraghav-cisco 
I saw the endless on a T0 testbed. 

> I will add a check to stop the infinite loop after 500 ip addresses, if that is ok. If none of the 500 src addresses work(the dst_port_id never got any of the packets, but there is other ports receive all the packets), then this is a problem, and a RuntimeError will be raised.

This check looks good to me. But I still suggest limiting the change to multiasic for now, as we did in PR https://github.com/sonic-net/sonic-mgmt/pull/8774. 

Adding @XuChen-MSFT to commet.

2023-07-25 03:32 UTC, XuChen-MSFT commented
@rraghav-cisco  @bingwang-ms  @wangxin  @StormLiangMS  @vmittal-msft 
suggest to quickly fix by checking max loop count first.
At this stage, there is a risk for only applying get_multiple_flow, it might cause test unstable for couple of weeks.
But, eventually, we need Raghav help to investigate solution of limiting this change to multiasic, and make a seperate PR to fix in the near further.

2023-07-25 15:29 UTC, XuChen-MSFT commented
@rraghav-cisco 

Could you please to prepare a new PR to quickly fix this infinite loop issue by check max loop count ASAP?

+  @bingwang-ms @wangxin @StormLiangMS @vmittal-msft for vis

2023-07-25 16:15 UTC, rraghav-cisco commented
@bingwang-ms , @wangxin @StormLiangMS @vmittal-msft : Pls check https://github.com/sonic-net/sonic-mgmt/pull/9112

2023-08-09 06:12 UTC, XuChen-MSFT commented
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis