VLAN to VNI not implemented loganalyzer error
sonic-net/sonic-mgmt pull request #8621
Opened 2023-06-15 18:40 UTC by CharudattaSChitale

Description:  
Seeing a loganalyzer error 'ERR syncd#syncd: SAI_LOG|SAI_API_TUNNEL:VLAN to VNI not implemented yet' when running decap/test_decap.py script. the SDK code that dumps that message is the old code, has been there since 2021.
It's dumped when create tunnel with type of VLAN to VNI.
In the test sonic-mgmt code, decap/test_decap.py doesn't have new change to add that, probably some common code, since it's harmless and cases can pass, proposing to add this message to ignore list.

Changes: 
Adding a line 'r, ".* ERR syncd#syncd:.*SAI_LOG|SAI_API_TUNNEL: VLAN to VNI not implemented yet.*"' to loganalyzer_common_ignore.txt file.

Description: 
In Dualtor/test_orchagent_mac_move.py, when doing active forwarding check after fdb ageout/flush, traffic gets flooded in vlan for cisco and Mellanox platforms. Because of this, the testcase fails. To avoid this, skip condition is added for Mellanox platforms. This PR is including the same skip condition for Cisco platforms as well.

Changes: 
Put 'cisco-8000' in the skip condition along with Mellanox
if not (tor.facts['asic_type'] == 'mellanox' or tor.facts['asic_type'] == 'cisco-8000'):
tor.shell("fdbclear")
server_traffic_monitor = ServerTrafficMonitor(
tor, ptfhost, vmhost, tbinfo, test_port,
conn_graph_facts, exp_pkt, existing=False, is_mocked=is_mocked_dualtor(tbinfo) # noqa F405
)

Verification: 
The test was run on a T0 testbed after making above changes and it passed.

This PR needs to be backported to 202205 branch

2023-07-21 03:29 UTC, kevinskwang commented
The description is not aligned with the code change.
"In Dualtor/test_orchagent_mac_move.py, when doing active forwarding check after fdb ageout/flush, traffic gets flooded in vlan for cisco and Mellanox platforms. Because of this, the testcase fails. To avoid this, skip condition is added for Mellanox platforms. This PR is including the same skip condition for Cisco platforms as well."

2023-07-26 22:04 UTC, Aravind-Subbaroyan commented
@kevinskwang  - the description is updated now.

2023-09-15 03:44 UTC, kevinskwang commented
Why this error didn't happen on 8102/8101?

2023-10-23 22:39 UTC, CharudattaSChitale commented
The issue was seen on 8111 platform also

2023-12-20 07:26 UTC, kevinskwang commented
This PR is no longer required as the decap with vxlan_set was skipped on 8111.

2024-01-04 19:33 UTC, CharudattaSChitale commented
Closing this PR as its no longer required.

2024-01-18 21:20 UTC, CharudattaSChitale commented
Issue is still seen on M64 Dualtor Active-Active setup on 202305 branch.

2024-03-01 06:17 UTC, bpar9 approved these changes

2024-03-01 07:23 UTC, bpar9 requested changes
changes including this error have already been committed by Raghav. Please close this PR

2024-03-01 16:39 UTC, closed without merging