Cisco: qos-sai: Skip losslelss voq tests if hbm is detected
sonic-net/sonic-mgmt pull request #8914
Opened 2023-07-12 02:13 UTC by rraghav-cisco

For HBM, we use the default Voq, so the split-voq tests need to be skipped. This PR addresses the Lossless Voq test.
1. Introduce a new fixture to find if HBM is enabled in the DUT, using the dshell_client.
2. Use the new fixture for the LosslessQueueVoq tests.

2023-07-13 02:37 UTC, wangxin commented
@rraghav-cisco Is this PR a backport? Does master branch have the same issue?

2023-07-13 04:05 UTC, rraghav-cisco commented
@wangxin : No, it is a new PR in 202205 only. Master doesn't have this code at all.

2023-07-14 01:17 UTC, abdosi requested changes
as comment

2023-07-14 01:17 UTC, abdosi commented on tests/qos/qos_sai_base.py
> +
let's use platform check instead of determine if hbm is there or not

2023-07-20 20:30 UTC, abdosi approved these changes

2023-07-21 15:32 UTC, rraghav-cisco commented
@wangxin : Can you pls re-submit the azp run ? I am not sure the above fail is related to my changes. Thanks in advance.

2023-08-02 17:22 UTC, abdosi approved these changes

2023-08-02 17:23 UTC, abdosi commented
@wangxin please help merge this.

2023-08-03 20:38 UTC, rraghav-cisco commented
@rraghav-cisco : Add the list of tests that are being skipped, and add the testcase skips to this PR itself.

2023-08-03 20:39 UTC, abdosi requested changes
PR description needs update

2023-08-23 23:51 UTC, abdosi approved these changes

2023-08-28 06:51 UTC, merged