Add cisco HwSkus to qos-sai, gb list.
sonic-net/sonic-mgmt pull request #9072
Opened 2023-07-20 23:24 UTC by rraghav-cisco

Adding the cisco GB HwSkus to the ansible/group_vars/sonic/variables
These HwSkus have been used by Cisco and Microsoft for a while now.

2023-09-22 22:52 UTC, abdosi commented on ansible/group_vars/sonic/variables
> +cisco-8000_gb_hwskus: ["Cisco-8102-C64", "Cisco-88-LC0-36FH-M-O36", "Cisco-8101-O8C48", "Cisco-8101-O32"]
please add : Cisco-88-LC0-36FH-O36

2023-09-22 22:52 UTC, abdosi requested changes
as comment

2023-09-22 22:52 UTC, abdosi commented
please rebase.

2023-09-28 00:14 UTC, rraghav-cisco commented on ansible/group_vars/sonic/variables
> +cisco-8000_gb_hwskus: ["Cisco-8102-C64", "Cisco-88-LC0-36FH-M-O36", "Cisco-8101-O8C48", "Cisco-8101-O32"]
@abdosi : Done.

2023-10-04 19:38 UTC, rraghav-cisco commented
@abdosi : resolved conflicts.

2023-10-06 17:11 UTC, rraghav-cisco commented
The azp job failed in a mux-related code, not related to this PR.

2023-10-07 05:32 UTC, rraghav-cisco commented
@abdosi : Re-updated PR, all pre-checks have passed. Pls merge this.

2023-10-12 22:09 UTC, abdosi approved these changes

2023-10-12 22:10 UTC, merged

2023-10-13 01:03 UTC, mssonicbld commented
@rraghav-cisco PR conflicts with 202205 branch

2023-11-20 02:46 UTC, mssonicbld commented
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/10777

2023-11-21 19:34 UTC, rraghav-cisco commented
> @rraghav-cisco PR conflicts with 202205 branch
@mssonicbld : Raised for 202205: https://github.com/sonic-net/sonic-mgmt/pull/10822